import { defineArrayMember, defineField, defineType } from "sanity";

const narrativeField = (name: string, title: string) =>
  defineField({ name, title, type: "richText", group: "narrative" });

export const project = defineType({
  name: "project",
  title: "Project",
  type: "document",
  groups: [
    { name: "overview", title: "Overview", default: true },
    { name: "narrative", title: "Case narrative" },
    { name: "editorial", title: "Editorial layout" },
    { name: "media", title: "Media" },
  ],
  fields: [
    defineField({
      name: "title",
      title: "Title",
      type: "string",
      group: "overview",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      group: "overview",
      options: { source: "title", maxLength: 96 },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "year",
      title: "Year",
      type: "string",
      group: "overview",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "role",
      title: "Role",
      type: "string",
      group: "overview",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "discipline",
      title: "Discipline",
      type: "array",
      group: "overview",
      of: [defineArrayMember({ type: "string" })],
      options: { layout: "tags" },
      validation: (rule) => rule.min(1).required(),
    }),
    defineField({
      name: "domain",
      title: "Domain",
      type: "string",
      group: "overview",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "platform",
      title: "Platform",
      type: "array",
      group: "overview",
      of: [defineArrayMember({ type: "string" })],
      options: { layout: "tags" },
      validation: (rule) => rule.min(1).required(),
    }),
    defineField({
      name: "projectType",
      title: "Project type",
      type: "string",
      group: "overview",
      options: {
        list: [
          "UX research case",
          "Product design case",
          "Academic / Skilvul challenge",
          "Concept / exploration",
          "Playground / early practice",
        ],
      },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "featured",
      title: "Featured on homepage",
      type: "boolean",
      group: "overview",
      initialValue: false,
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "homepageOrder",
      title: "Homepage order",
      type: "number",
      group: "overview",
      validation: (rule) => rule.integer().min(1).required(),
    }),
    defineField({
      name: "shortSummary",
      title: "Short summary",
      type: "text",
      rows: 3,
      group: "overview",
      validation: (rule) => rule.max(260).required(),
    }),
    defineField({
      name: "statusNote",
      title: "Evidence / status note",
      type: "string",
      group: "overview",
      description:
        "Use this to disclose academic, concept, incomplete-evidence, or other material context.",
    }),
    defineField({
      name: "visualTone",
      title: "Editorial placeholder tone",
      type: "string",
      group: "overview",
      options: {
        list: ["orange", "ink", "blue", "green", "red"],
        layout: "radio",
      },
      initialValue: "orange",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "heroImage",
      title: "Hero image",
      type: "editorialImage",
      group: "media",
    }),
    defineField({
      name: "gallery",
      title: "Gallery",
      type: "array",
      group: "media",
      of: [defineArrayMember({ type: "editorialImage" })],
    }),
    narrativeField("context", "Context"),
    narrativeField("problem", "Problem"),
    narrativeField("users", "People / users"),
    narrativeField("constraints", "Constraints"),
    narrativeField("research", "Research"),
    narrativeField("findings", "Findings"),
    narrativeField("decisions", "Decisions"),
    narrativeField("tradeOffs", "Trade-offs"),
    narrativeField("testing", "Testing"),
    narrativeField("outcome", "Outcome"),
    narrativeField("reflection", "Reflection"),
    defineField({
      name: "externalLinks",
      title: "External links",
      type: "array",
      group: "overview",
      of: [defineArrayMember({ type: "externalLink" })],
    }),
    defineField({
      name: "sections",
      title: "Flexible project sections",
      type: "array",
      group: "editorial",
      of: [defineArrayMember({ type: "projectSection" })],
    }),
  ],
  orderings: [
    {
      title: "Homepage order",
      name: "homepageOrder",
      by: [{ field: "homepageOrder", direction: "asc" }],
    },
    {
      title: "Year, newest",
      name: "yearDesc",
      by: [{ field: "year", direction: "desc" }],
    },
  ],
  preview: {
    select: { title: "title", subtitle: "projectType", media: "heroImage" },
  },
});
